import {
  // fromUrl,
  // editorJson2A11yHtml,
  // html2editorJson,
  editorJson2Text,
  html2Text,
} from './src/index';

// import { readFile, writeFile } from 'fs';

// const loadHtmlFromFile = async (path: string): Promise<string> => {
//   return new Promise((resolve, reject) => {
//     readFile(path, (err, data) => {
//       if (err) {
//         reject(err);
//       } else {
//         resolve(data.toString());
//       }
//     });
//   });
// };

// const saveHtmlToFile = async (path: string, html: string): Promise<void> => {
//   return new Promise((resolve, reject) => {
//     writeFile(path, html, (err) => {
//       if (err) {
//         reject(err);
//       } else {
//         resolve();
//       }
//     });
//   });
// };

// (async () => {
//   const beforeFn = ` ($) => {
//     console.log('beforeFn hook');
//   }`;
//   const afterFn = ` ($) => {
//     console.log('afterrr hook');
//   }`;
//   const url =
//     'https://www.city.fukuoka.lg.jp/hofuku/coronavaccine/wakutin.html';
//   // 'http://127.0.0.1:5500/index.html';
//   // 'https://www.city.yatsushiro.lg.jp/kiji00318310/index.html';
//   // 'https://www.city.yatsushiro.lg.jp/kiji00312980/index.html';
//   const { html, body } = await fromUrl({
//     url,
//     // opt: {
//     //   contentSelectors: ['.container'],
//     //   hooks: {
//     //     before: beforeFn,
//     //     after: afterFn,
//     //   },
//     // },
//   });
//   await saveHtmlToFile('./data/test1-out.html', html || '');

//   const { json, meta: metaOpts } = html2editorJson(
//     `<html><head lang="ja"><title>【城南区】城南体育館の教室</title><meta name="viewport" content="width=device-width, initial-scale=1"><meta charset="utf-8"><meta http-equiv="X-UA-Compatible" content="IE=edge"><link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin=""><link rel="stylesheet" href="https://unpkg.com/a11y-css-reset/combo.css"><link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Noto+Sans+JP:wght@100;300;400;500;700;900&amp;display=swap"><link rel="stylesheet" href="https://ragt-dev.s3.ap-southeast-1.amazonaws.com/public/ragt-convertor/ja.css"></head><body id="skg-style"><p>【城南区】城南体育館の教室<br/><br/>【場所・問い合わせ】<br/>城南体育館<br/>電話 092-851-0303<br/>FAX 092-851-0040<br/><br/>【料金】<br/>各4,500円(全10回分)<br/><br/>【定員】<br/>各抽選29人<br/><br/>【対象】<br/>18歳以上<br/><br/>【申し込み】<br/>12月16日までに同体育館で配布する申込書に記入の上、お申し込みください。<br/><br/>【教室名・開催日時】<br/>・やさしいピラティス　　1月6日から3月10日の金曜日　午後3時15分から4時45分<br/>・夜ヨガ　　　　　　　　1月10日から3月14日の火曜日　午後7時15分から8時45分<br/>・やさしいエアロビクス　1月10から3月14日の火曜日　　午前11時半から午後0時半<br/>・リフレッシュヨガ　　　1月11日から3月15日の水曜日　午前11時10分から午後0時40分<br/>・ZUMBA(ズンバ)　　　　1月13日から3月17日の金曜日　午前11時から正午<br/>・50歳から始める優しい運動教室　1月26日から3月30日の木曜日　午後1時半から3時<br/><br/>ここに「開催日時表」の画像があります。<br/>https://www.city.fukuoka.lg.jp/data/open/cnt/3/101072/1/221201_3jhonan_6.jpg?20221125092148<br/><br/></p></body></html>`
//   );
//   const { html: a11yHtml1, meta } = editorJson2A11yHtml(json, metaOpts);

//   // save meta data
//   await saveHtmlToFile('./data/test1-json.json', JSON.stringify(json));

//   await saveHtmlToFile('./data/test1-ragt.html', a11yHtml1 || '');

//   await saveHtmlToFile('./data/test1-meta.json', JSON.stringify(meta));

// })();

(() => {
  const ragtJson = {
    metaOpt: {
      lang: 'ja',
      title: '',
      description: '',
      favicon: '',
      image: '',
    },
    blocks: [
      {
        id: 'ru0nDiNjp9',
        type: 'paragraph',
        data: {
          text: 'paragraph 1',
        },
        meta: [
          {
            ui: 'paragraph 1',
            polly: 'paragraph 1',
            ssml: '',
            user: '',
            actions: [],
            id: 'b859495e-8040-4f19-bd18-75f9aca0b950',
          },
        ],
      },
      {
        id: '_XnqdkMvju',
        type: 'header',
        data: {
          text: 'heading',
          level: 2,
        },
        meta: [
          {
            ui: 'heading',
            polly: 'heading',
            ssml: '',
            user: '',
            actions: [],
            id: 'c60ed830-339a-4ca3-a3d2-3dfb9983d255',
          },
        ],
      },
      {
        id: '9PlZD7IJfA',
        type: 'list',
        data: {
          style: 'ordered',
          items: [
            {
              content: 'level 1',
              items: [],
            },
            {
              content: 'level 2',
              items: [
                {
                  content: 'level 2.1',
                  items: [],
                },
                {
                  content: 'level 2.2',
                  items: [],
                },
              ],
            },
          ],
        },
        meta: [
          {
            ui: 'これは箇条書きのリストで, 2個の項目と2個のサブ項目があります。',
            polly:
              'これは番号付きリストで, 2個の項目と2個のサブ項目があります。',
            ssml: '',
            user: '',
            actions: [],
            isAutogenerated: true,
            id: '9f6568b0-f02a-469e-9706-76303781b39b',
          },
          {
            parentId: 'root',
            id: '7xszlm',
            ui: 'level 1',
            polly: 'level 1',
            ssml: '',
            user: '',
            actions: [null],
          },
          {
            parentId: 'root',
            id: 'd8naqu',
            ui: 'level 2',
            polly: 'level 2',
            ssml: '',
            user: '',
            actions: [null],
          },
          {
            parentId: 'd8naqu',
            id: '3fsh25',
            ui: 'level 2.1',
            polly: 'level 2.1',
            ssml: '',
            user: '',
            actions: [null],
          },
          {
            parentId: 'd8naqu',
            id: 'of2syn',
            ui: 'level 2.2',
            polly: 'level 2.2',
            ssml: '',
            user: '',
            actions: [null],
          },
        ],
      },
      {
        id: 'Aphjmoq_Tg',
        type: 'image',
        data: {
          file: {
            url: 'https://s3-univoice-dev.s3.ap-southeast-1.amazonaws.com/ragt-editor/2b5a5362-afd1-4621-be65-b65b18834c44',
          },
          caption: 'image caption',
          withBorder: false,
          stretched: false,
          withBackground: false,
        },
        meta: [
          {
            ui: 'image caption',
            polly: 'ここに「image caption」の画像があります。',
            ssml: '',
            user: '',
            actions: [],
            id: 'dc11f91a-b007-4c94-977a-45e4696f1366',
          },
        ],
      },
      {
        id: 'CScSRrrRwo',
        type: 'table',
        data: {
          withHeadings: true,
          content: [
            ['header 1', 'header 2'],
            ['cell 1', 'cell 2'],
          ],
        },
        meta: [
          {
            id: 'whso3h',
            ui: 'この下に、縦2行、横2列の表があります。\n見出し行は左からheader 1、header 2です。',
            polly: 'この下に、縦2行、横2列の表があります。',
            ssml: '',
            user: '',
            actions: [],
            isAutogenerated: true,
          },
          {
            ui: '<tr tabindex="0" aria-label="データの1行目、header 1、header 2、"><th aria-hidden="true">header 1</th><th aria-hidden="true">header 2</th></tr>',
            polly: 'データの1行目、header 1、header 2、',
            ssml: '',
            user: '',
            actions: [],
            id: 'c3e5dd58-c8f0-44a4-8e8f-8875177a4d6f',
          },
          {
            ui: '<tr tabindex="0" aria-label="2行目、cell 1、cell 2です。"><td aria-hidden="true">cell 1</td><td aria-hidden="true">cell 2</td></tr>',
            polly: '2行目、cell 1、cell 2です。',
            ssml: '',
            user: '',
            actions: [],
            id: 'faaa0dc6-ae80-48ca-acd9-4e979ee88c9d',
          },
          {
            id: 'vnn489',
            ui: '表の終わりです。',
            polly: '表の終わりです。',
            ssml: '',
            user: '',
            actions: [],
            isAutogenerated: true,
          },
        ],
      },
    ],
  };
  // console.log(editorJson2Text(ragtJson));

  html2Text({
    html: `
<?xml version="1.0" encoding="utf-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html lang="ja" xml:lang="ja" xmlns="http://www.w3.org/1999/xhtml">
<head prefix="og: http://ogp.me/ns# fb: http://ogp.me/ns/fb# article: http://ogp.me/ns/article#">
<meta property="og:type"   content="article" />
<meta property="og:url"    content="https://www.town.agui.lg.jp/contents_detail.php?frmId=71" />
<meta property="og:title"  content="産業観光課農政係の仕事 | 阿久比町" />
<meta property="og:image"  content="https://www.town.agui.lg.jp/images/logo_images.jpg" />

<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta http-equiv="Content-Language" content="ja" />
<meta http-equiv="Content-Style-Type" content="text/css" />
<meta http-equiv="Content-Script-Type" content="text/javascript" />
<title>産業観光課農政係の仕事 | 阿久比町</title>
<script type="text/javascript">
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-71444537-1', 'auto');
  ga('send', 'pageview');

</script><script type="text/javascript" src="js/jquery-1.11.3.min.js"></script>
<!-- on  -->
<script type="text/javascript" src="js/toolbox-ssl.js"></script>
<script type="text/javascript" src="js/google_bg.js"></script>
<script type="text/javascript" src="css/img/twitter.js"></script>
<script type="text/javascript" src="css/img/facebook.js"></script>
<link rel="stylesheet" type="text/css" href="css/style.css?123" media="screen,print" />
<link rel="stylesheet" type="text/css" href="css/molecule_view.css?123" media="screen,print" />
<link rel="stylesheet" type="text/css" href="css/faq.css" media="screen,print" />
<!--[if IE 7]>
<link rel="stylesheet" type="text/css" href="css/ie70.css?123" media="screen,print" />
<![endif]-->
<!--[if IE 8]>
<link rel="stylesheet" type="text/css" href="css/ie80.css?123" media="screen,print" />
<![endif]-->
<!--[if IE 9]>
<link rel="stylesheet" type="text/css" href="css/ie90.css?123" media="screen,print" />
<![endif]-->
<link rel="stylesheet" type="text/css" href="css/print.css?123" media="print" />
<link href="css/img/favicon.ico" rel="shortcut icon" />
<script type="text/javascript">
$(function(){
    $("dl.mol_attachfileblock_adobe").each(function(){
        if($(this).find("a").attr('href') == 'http://www.microsoft.com/downloads/details.aspx?displaylang=ja&FamilyID=3657ce88-7cfa-457a-9aec-f4f827f20cac'){
            $(this).hide();
        }
        if($(this).find("a").attr('href') == 'http://www.microsoft.com/downloads/details.aspx?displaylang=ja&FamilyID=1cd6acf9-ce06-4e1c-8dcf-f33f669dbc3a'){
            $(this).hide();
        }

    });
});
</script>


</head>
<body id="body" class="inbody inkiji" onload="getCookie();">
<a name="pagetop" id="pagetop" class="anchor" tabindex="-1"><img src="images/clearspacer.gif" alt="ページの先頭です" width="1" height="1" /></a>
<div class="all">
<div class="design">

<!-- ▼▼▼▼▼ヘッダ▼▼▼▼▼ -->
<div id="head_bg">
<div id="head" class="clear">
<!--head_sub-->
<div id="head_sub" class="clear">
<!--head_sub_lower01-->
<div id="head_sub_lower01">
<ul id="head_links">
<li><a href="#HONBUN"><img src="/css/img/head_to.png" alt="本文へ" /></a></li><li><a href="http://www.town.agui.lg.jp/m/"><img src="/cmsfiles/menu_img/menu-34.png" alt="携帯サイト" /></a></li><li><a href="https://www.town.agui.lg.jp/form/opinion.cgi"><img src="/cmsfiles/menu_img/menu-35.png" alt="町政へのご意見" /></a></li></ul><div class="link_box">
<ul class="clear">
<li><a href="/soshiki_list.php"><img src="/css/img/in_head_org.gif" alt="組織で探す" /></a></li><li><a href="/sitemap.php"><img src="/css/img/in_head_map.gif" alt="サイトマップ" /></a></li>
</ul>
</div><div class="search_box">
<form action="https://www.google.com/cse" id="search_form" name="search_form"><input type="hidden" name="cx" value="004813469845189942980:xlvcg0ykuje" /><input type="hidden" name="ie" value="UTF-8" /><input type="text" id="q" name="q" title="検索キーワード" /><input type="image" src="/css/img/search.gif" id="search_button" name="search_button" alt="サイト内検索" /></form>
</div>
</div>
<!--/head_sub_lower01-->
<!--head_sub_lower02-->
<div id="head_sub_lower02" class="clear">
<div id="head_lang">
<p lang="en" xml:lang="en"><img src="/css/img/lang.gif" alt="翻訳" /></p><ul class="clear">
<!--IF_TRANS_HIDE:ja <li><a href="https://www.town.agui.lg.jp/"><img src="/css/img/head_ja.gif" alt="日本語" width="50" height="21"  /></a></li> /IF_TRANS_HIDE:ja-->
<!--IF_TRANS_HIDE:en--><li><a onclick="window.translate('en');" href="javascript:void(0)" lang="en" xml:lang="en"><img alt="English" src="/css/img/in_head_en.gif" /></a></li><!--/IF_TRANS_HIDE:en-->
<!--IF_TRANS_HIDE:ko--><li><a onclick="window.translate('ko');" href="javascript:void(0)" lang="ko" xml:lang="ko"><img src="/css/img/in_head_ko.gif" alt="한국" /></a></li><!--/IF_TRANS_HIDE:ko-->
<!--IF_TRANS_HIDE:zhb--><li><a onclick="window.translate('zhb');" href="javascript:void(0)" lang="zh-tw" xml:lang="zh-tw"><img src="/css/img/in_head_cn.gif" alt="中文繁體" /></a></li><!--/IF_TRANS_HIDE:zhb-->
<!--IF_TRANS_HIDE:zh--><li><a onclick="window.translate('zh');" href="javascript:void(0)" lang="zh" xml:lang="zh"><img alt="中文簡体" src="/css/img/in_head_zh.gif" /></a></li><!--/IF_TRANS_HIDE:zh-->
<!--IF_TRANS_HIDE:pt--><li><a onclick="window.translate('pt');" href="javascript:void(0)" lang="pt" xml:lang="pt"><img src="/css/img/in_head_pt.gif" alt="Portugues" /></a></li><!--/IF_TRANS_HIDE:pt-->
</ul>
</div>
<div class="font">
<p class="font_size"><img src="/css/img/font.gif" alt="文字" /></p><ul class="font_size"><li><a href="javascript:textSizeReset();"><img src="/css/img/font_def.gif" alt="標準" /></a></li><li><a href="javascript:textSizeUp();"><img src="/css/img/font_big.gif" alt="拡大" /></a></li></ul>
</div>
</div>
<!--/head_sub_lower02-->
</div>
<!--/head_sub-->

<div id="head_main" class="clear">
<div class="h1"><a href="/"><img src="/design_img/head_id.png?123" alt="阿久比町" /></a></div>
</div>

<div id="navi">
<ul class="clear">
<li class="menu_hom"><a href="https://www.town.agui.lg.jp/" onmouseover="change_image('menu809',810)" onfocus="change_image('menu809',810)" onmouseout="change_image('menu809',809)" onblur="change_image('menu809',809)"><img src="/css/img/in_navi_hom2.png" alt="ホーム"  name="menu809" id="menu809" /></a></li>
<li class="menu_lif"><a href="https://www.town.agui.lg.jp/category_list.php?frmCd=8-0-0-0-0" onmouseover="change_image('menu811',812)" onfocus="change_image('menu811',812)" onmouseout="change_image('menu811',811)" onblur="change_image('menu811',811)"><img src="/css/img/in_navi_inf2.png" alt="町の紹介"  name="menu811" id="menu811" /></a></li><li class="menu_lif"><a href="https://www.town.agui.lg.jp/category_list.php?frmCd=1-0-0-0-0" onmouseover="change_image('menu801',802)" onfocus="change_image('menu801',802)" onmouseout="change_image('menu801',801)" onblur="change_image('menu801',801)"><img src="/css/img/in_navi_lif2.png" alt="暮らし"  name="menu801" id="menu801" /></a></li><li class="menu_hlt"><a href="https://www.town.agui.lg.jp/category_list.php?frmCd=9-0-0-0-0" onmouseover="change_image('menu803',804)" onfocus="change_image('menu803',804)" onmouseout="change_image('menu803',803)" onblur="change_image('menu803',803)"><img src="/css/img/in_navi_hlt2.png" alt="健康づくり"  name="menu803" id="menu803" /></a></li><li class="menu_car"><a href="https://www.town.agui.lg.jp/category_list.php?frmCd=10-0-0-0-0" onmouseover="change_image('menu805',806)" onfocus="change_image('menu805',806)" onmouseout="change_image('menu805',805)" onblur="change_image('menu805',805)"><img src="/css/img/in_navi_car2.png" alt="福祉・医療" name="menu805" id="menu805" /></a></li><li class="menu_gmt"><a href="https://www.town.agui.lg.jp/category_list.php?frmCd=4-0-0-0-0" onmouseover="change_image('menu807',808)" onfocus="change_image('menu807',808)" onmouseout="change_image('menu807',807)" onblur="change_image('menu807',807)"><img src="/css/img/in_navi_gmt2.png" alt="町政情報"  name="menu807" id="menu807" /></a></li></ul>
</div>

<noscript><p class="noscript"><strong>文字サイズ変更機能を利用するにはJavaScript（アクティブスクリプト）を有効にしてください。JavaScript（アクティブスクリプト） を無効のまま文字サイズを変更する場合には、ご利用
のブラウザの表示メニューから文字サイズを変更してください。</strong></p></noscript>


</div>
</div>
<a id="HONBUN" class="anchor" tabindex="-1"><img src="/images/clearspacer.gif" alt="" width="1" height="1" /></a>
<!-- <olang> --><input type="hidden" id="ssps" value="http://www.town.agui.lg.jp/contents_detail.php?co=kak&frmId=71"/><!-- </olang> -->
<!-- ▲▲▲▲▲ヘッダ▲▲▲▲▲ -->
<!-- ▼▼▼▼▼メイン▼▼▼▼▼ -->
<ul id="pankuzu" class="clear">
<li><a href="/">ホーム</a></li>
<li><a href="soshiki_list.php">各課の窓口</a></li>
<li><a href="soshiki_view.php?so_cd1=3&amp;so_cd2=1&amp;so_cd3=1&amp;so_cd4=0&amp;so_cd5=0">農政係</a></li>
<li><a href="soshiki_view.php?so_cd1=3&amp;so_cd2=1&amp;so_cd3=1&amp;so_cd4=0&amp;so_cd5=0&amp;bn_cd=1">お知らせ</a></li>
</ul>
<div class="main_naka">
<h1>産業観光課農政係の仕事</h1>
<div class="clear">
<p class="syosai_hiduke">[2012年4月1日]</p>
<div id="sns_box">
<p class="sns_btn"><span class="small">ソーシャルサイトへのリンクは別ウィンドウで開きます</span></p>
<ul>
<li class="sns_btn"><script type="text/javascript">facebutton();</script></li>
<li class="sns_btn"><script type="text/javascript">twitterbutton();</script></li>
</ul>
</div>
</div>
</div>
</div>

<div class="waku">
<div class="clear">
<div class="main_naka_kiji_box">
<div class="main_naka_kiji">
<div id="mol_contents" class="mol_contents"><div class="mol_textblock"><ul><li>農業委員会に関すること。</li><li>農地に関すること。</li><li>農業者年金に関すること。</li><li>農林業振興に関すること。</li><li>農業振興地域整備計画に関すること。</li><li>食育推進計画に関すること。</li><li>農業経営基盤強化促進事業に関すること。</li><li>米生産調整に関すること。</li><li>農林水産統計に関すること。</li><li>病害虫防除に関すること。</li><li>家畜伝染病に関すること。</li><li>林地保全に関すること。</li><li>治山、治水に関すること。</li><li>緑化推進に関すること。</li><li>鳥獣保護および狩猟に関すること。</li><li>知多地区農業共済事務組合に関すること。</li><li>知多南部総合卸売市場に関すること。</li></ul></div></div>
</div>
</div>
<div id="kiji_sub">
<div class="syosai_sonota">
<h2>お問い合わせ</h2>
<p>阿久比町役場建設経済部<br />産業観光課農政係</p>
<p>電話: 0569-48-1111<br />&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;内線1222・1223</p><p>ファックス: 0569-48-0229</p><p class="for_img"><strong><img src="css/img/sonota_atc.gif" alt="電話番号のかけ間違>いにご注意ください！" width="160" height="42" /></strong></p>
<p><a href="https://www.town.agui.lg.jp/form/inquiry.cgi?so=277da6cc975c9c0fc7b6af8e75afb98095dba73c&amp;ref=%2Fcontents_detail.php%3Fco%3Dkak%26frmId%3D71">
<img src="css/img/sonota_btn.gif" alt="お問い合わせフォーム" width="160" height="30" />
</a></p></div><div class="kakuka">
<h2>組織内ジャンル</h2>
<h3>建設経済部産業観光課農政係</h3>
<ul style="margin:0 0 8px 0;">
<li><a href="soshiki_view.php?so_cd1=3&amp;so_cd2=1&amp;so_cd3=1&amp;so_cd4=0&amp;so_cd5=0&amp;bn_cd=1">お知らせ</a>
</li>
<li><a href="soshiki_view.php?so_cd1=3&amp;so_cd2=1&amp;so_cd3=1&amp;so_cd4=0&amp;so_cd5=0&amp;bn_cd=3">農業者支援</a>
</li>
<li><a href="soshiki_view.php?so_cd1=3&amp;so_cd2=1&amp;so_cd3=1&amp;so_cd4=0&amp;so_cd5=0&amp;bn_cd=4">元気な家族農園</a>
</li>
<li><a href="soshiki_view.php?so_cd1=3&amp;so_cd2=1&amp;so_cd3=1&amp;so_cd4=0&amp;so_cd5=0&amp;bn_cd=5">畜産</a>
</li>
<li><a href="soshiki_view.php?so_cd1=3&amp;so_cd2=1&amp;so_cd3=1&amp;so_cd4=0&amp;so_cd5=0&amp;bn_cd=6">鳥獣</a>
</li>
<li><a href="soshiki_view.php?so_cd1=3&amp;so_cd2=1&amp;so_cd3=1&amp;so_cd4=0&amp;so_cd5=0&amp;bn_cd=7">食育</a>
</li>
<li><a href="soshiki_view.php?so_cd1=3&amp;so_cd2=1&amp;so_cd3=1&amp;so_cd4=0&amp;so_cd5=0&amp;bn_cd=8">林務</a>
</li>
<li><a href="soshiki_view.php?so_cd1=3&amp;so_cd2=1&amp;so_cd3=1&amp;so_cd4=0&amp;so_cd5=0&amp;bn_cd=2">農業振興</a>
</li>
</ul>
</div></div>
</div>
</div>
<img src="images/clearspacer.gif" alt="" width="100%" height="1" />

<div class="design">
<div class="main_naka">
<!-- ▼▼▼▼▼アンケート領域▼▼▼▼▼ -->
<div class="syosai_qa">
<div class="syosai_qa2">
<form class="form" name="mdb" action="https://www.town.agui.lg.jp/evaluation/evaluation.cgi" method="post">
<h2>ご意見をお聞かせください</h2>
<div>
<ul><li><fieldset><legend>このページは役に立ちましたか？</legend>
<p><span><input type="radio" name="ans1" id="ans12" value="2" /><input type="hidden" name="ans1_2_text" value="役に立った" /><label for="ans12">役に立った</label></span>
<span><input type="radio" name="ans1" id="ans11" value="1" /><input type="hidden" name="ans1_1_text" value="まあまあ役に立った" /><label for="ans11">まあまあ役に立った</label></span>
<span><input type="radio" name="ans1" id="ans10" value="0" checked="checked" /><input type="hidden" name="ans1_0_text" value="どちらともいえない" /><label for="ans10">どちらともいえない</label></span>
<span><input type="radio" name="ans1" id="ans1-1" value="-1" /><input type="hidden" name="ans1_-1_text" value="あまり役に立たなかった" /><label for="ans1-1">あまり役に立たなかった</label></span>
<span><input type="radio" name="ans1" id="ans1-2" value="-2" /><input type="hidden" name="ans1_-2_text" value="役に立たなかった" /><label for="ans1-2">役に立たなかった</label></span>
</p>
</fieldset>
</li>
<li>
<fieldset>
<legend>このページは見つけやすかったですか？</legend>
<p><span><input type="radio" name="ans2" id="ans22" value="2" /><input type="hidden" name="ans2_2_text" value="見つけやすかった" /><label for="ans22">見つけやすかった</label></span>
<span><input type="radio" name="ans2" id="ans21" value="1" /><input type="hidden" name="ans2_1_text" value="まあまあ見つけやすかった" /><label for="ans21">まあまあ見つけやすかった</label></span>
<span><input type="radio" name="ans2" id="ans20" value="0" checked="checked" /><input type="hidden" name="ans2_0_text" value="どちらともいえない" /><label for="ans20">どちらともいえない</label></span>
<span><input type="radio" name="ans2" id="ans2-1" value="-1" /><input type="hidden" name="ans2_-1_text" value="やや見つけにくかった" /><label for="ans2-1">やや見つけにくかった</label></span>
<span><input type="radio" name="ans2" id="ans2-2" value="-2" /><input type="hidden" name="ans2_-2_text" value="見つけにくかった " /><label for="ans2-2">見つけにくかった </label></span>
</p>
</fieldset>
</li>
</ul>
</div>
<p><label for="opinion">このページに関してのご意見がありましたらご記入ください。</label></p>
<p>（注意）お答えが必要なお問合せは、直接担当部署へお願いいたします（こちらではお受けできません）。</p>
<textarea name="ans3" id="opinion" rows="3" cols="100"></textarea>
<div class="qa_button">
<input type="hidden" name="mode" value="check" />
<input type="hidden" name="con" value="71" />
<input type="submit" value="送信" />
</div>
</form>
</div>
</div>
<!-- ▲▲▲▲▲アンケート領域▲▲▲▲▲ -->


<hr />
</div>
<!-- ▲▲▲▲▲メイン▲▲▲▲▲ -->

<!-- ▼▼▼▼▼フッタ▼▼▼▼▼ -->
<input type="hidden" id="mainURLpath" value="/"/>
<div id="foot_bg">
<p id="foot_modori"><a href="#pagetop"><img src="/css/img/page_top.gif" alt="ページの先頭へ戻る" /></a></p>
<div id="foot" class="clear">
<div class="foot_main">
<ul id="foot_link"><li><a href="http://www.town.agui.lg.jp/contents_detail.php?frmId=548">阿久比町までの交通案内</a></li><li><a href="https://www.town.agui.lg.jp/site_policy.php?no=2">このサイトについて</a></li></ul><div id="foot_id" class="clear">
<img src="/css/img/foot_id.gif" alt="阿久比町役場" />
<address><span class="small">〒470-2292 愛知県知多郡阿久比町大字卯坂字殿越50番地</span></address>
<address class="small">電話: 0569-48-1111（代表）ファックス: 0569-48-0229（代表）</address><p class="small">役場開庁時間：午前8時30分～午後5時15分</p>
<p class="small">閉庁日：土曜日、日曜日、祝日、年末年始（12月29日～1月3日）</p>
<p class="small">利用者が情報を送信するページについてはSSL化（通信の暗号化）をしています。</p>
</div>
</div>
</div>
<address id="foot_copy" lang="en" xml:lang="en"><strong>Copyright ⓒ AGUI TOWN 2010. All right reserved.</strong></address>
</div>

<!-- ▲▲▲▲▲フッタ▲▲▲▲▲ -->
<script type="text/javascript" src="/js/onload_common.js"></script>
<div id="view_sp" style="display:none;"><a href="javascript:void(0);" onclick="subDelPc(); location.href=location.href.replace(/#.*$/,''); return false;">スマートフォン版ページへ</a></div>
</div>
</div>
<script type="text/javascript" src="/_Incapsula_Resource?SWJIYLWA=719d34d31c8e3a6e6fffd425f7e032f3&ns=67&cb=1727166697" async></script></body>
</html>`,
    contentSelectors: ['#body > div'],
    titleSelector: '#body > div > div:nth-child(1) > div.main_naka > h1',
    iArticle: {
      title: '1234',
      publishDate: '1234',
      loadedUrl: 'https://baodang.com/test',
    },
  }).then((res) => {
    console.log(res.a11yHTML);
  });
})();
