declare type MetaOptions = {
  title?: string;
  cssLinks?: string[];
  meta?: {};
  socialMeta?: {};
  lang?: string;
  favicon?: string;
  googleAnalyticsId?: string;
};

declare type ProcessOptions = {
  removeComments?: boolean;
  removeEmptyElements?: boolean;
  removeScriptTypeAttributes?: boolean;
  removeOptionalTags?: string[];
  removeSmallImages?: {
    minWidth: number;
    minHeight: number;
  };
  url?: string; // url of the page
  contentSelectors?: string[]; // selector of the content
  hooks?: {
    before?: string;
    after?: string;
  };
};

declare type MetaItem = {
  id?: string;
  ui?: string;
  polly?: string;
  ssml?: string;
  user?: string;
  actions?: string[];
  isAutogenerated?: boolean;
};

declare type BlockItem = {
  id?: string;
  data: {
    text?: string;

    // Heading
    level?: number;

    // List
    item?: any;
    style?: string;

    // Image
    caption?: string;
    file?: {
      url?: string;
    };
    stretched?: boolean;
    withBackground?: boolean;
    withBorder?: boolean;

    // Table
    content?: any;
  };
  meta: any;
  type: string;
};

declare type IArticle = {
  id: string;
  title: string;
  publishDate: string;
  crawledAt: string;
  URL: string;
  description: string;
  thumbnailURL?: string;
  topic?: string | string[];
  loadedUrl?: string;

  // IF can be added many more fields
  [key: string]: any;
};
